#!/usr/bin/env bash
# Usage: scripts/pin-engine.sh <engine-version>
# Downloads each coven-code release archive for OpenCoven/coven-code v<version>,
# computes sha256, and rewrites crates/coven-cli/engine.lock. Requires gh.
set -euo pipefail
VERSION="${1:?usage: pin-engine.sh <version>}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOCK="$REPO_ROOT/crates/coven-cli/engine.lock"

sha256() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print $1}';
  else shasum -a 256 "$1" | awk '{print $1}'; fi
}

ASSETS=$(gh release view "v${VERSION}" --repo OpenCoven/coven-code --json assets -q '.assets[].name')

# Collect coven-code-* asset lines and count them before touching the lock file.
engine_assets=""
count=0
for asset in $ASSETS; do
  case "$asset" in
    coven-code-*)
      engine_assets="$engine_assets $asset"
      count=$((count + 1))
      ;;
  esac
done
if [ "$count" -lt 5 ]; then
  echo "error: expected >=5 engine archives for v${VERSION}, got $count" >&2
  exit 1
fi

{
  echo '# Generated by scripts/pin-engine.sh — do not edit by hand.'
  echo "version = \"${VERSION}\""
  echo "contract = ${2:-1}"
  echo
  echo '[sha256]'
  for asset in $engine_assets; do
    tmp=$(mktemp)
    gh release download "v${VERSION}" --repo OpenCoven/coven-code --pattern "$asset" --output "$tmp" --clobber
    sum=$(sha256 "$tmp")
    rm -f "$tmp"
    echo "\"${asset}\" = \"${sum}\""
  done
} > "$LOCK"
echo "pinned engine ${VERSION} in ${LOCK}"
